#!/usr/bin/env ruby

require 'bundler/setup'

require 'commands'
require 'readline'

def exit_command?(line)
  line.nil? || !!(/^\s*exit/ =~ line)
end

@parser = Commands.parser
puts "Welcome to dnd helper v0.1"
puts "What should we do first?"
loop do
  line = Readline::readline('> ')
  break if exit_command?(line)
  action = @parser.parse(line)
  action.confirmation?
  action.apply
  puts action.log
  Readline::HISTORY.push(line)
end

exit
