#!/usr/bin/env ruby

require 'bundler/setup'

require 'commands'

def exit_command?
  !!(/^\s*exit/ =~ @last_command)
end

@parser = Commands.parser
puts "Welcome to dnd helper v0.1"
puts "What should we do first?"
loop do
  print '#>'
  @last_command = gets
  puts @last_command
  action = @parser.parse(@last_command)
  puts action
  action.confirmation?
  action.apply
  puts action.log
  break if exit_command?
end

exit
